version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.13

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            pytest tests/test_.*py
